
package pe.egcc.censoapp.view;

import pe.egcc.censoapp.controller.CensoController;
import pe.egcc.censoapp.model.Item;

/**
 *
 * @author DOCENTE
 */
public class ResumenView extends javax.swing.JInternalFrame {

  /**
   * Creates new form ResumenView
   */
  public ResumenView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblCaso1A = new javax.swing.JLabel();
    lblCaso1B = new javax.swing.JLabel();
    btnLeerEstadistica = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    lblCaso2A = new javax.swing.JLabel();
    lblCaso2B = new javax.swing.JLabel();

    setBorder(null);
    setClosable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("RESUMEN DE CENDO");

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("HOMBRES Y MUJERES"));

    lblCaso1A.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblCaso1A.setText("Hombres:");

    lblCaso1B.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblCaso1B.setText("Mujeres:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblCaso1A, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblCaso1B, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(55, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(lblCaso1A, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22)
        .addComponent(lblCaso1B, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(44, Short.MAX_VALUE))
    );

    btnLeerEstadistica.setText("Leer estadistica");
    btnLeerEstadistica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLeerEstadisticaActionPerformed(evt);
      }
    });

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("MAYORES DE EDAD - TODOS"));

    lblCaso2A.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblCaso2A.setText("Hombres:");

    lblCaso2B.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblCaso2B.setText("Mujeres:");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblCaso2A, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblCaso2B, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(55, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(lblCaso2A, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22)
        .addComponent(lblCaso2B, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(44, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnLeerEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(426, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnLeerEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(321, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnLeerEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerEstadisticaActionPerformed
    CensoController control = new CensoController();
    // Primer caso
    Item[] repo = control.obtenerEstadistico1();
    lblCaso1A.setText(repo[0].getCriterio() + ": " + repo[0].getValor());
    lblCaso1B.setText(repo[1].getCriterio() + ": " + repo[1].getValor());
    // Segundo caso
    repo = control.obtenerEstadistico2();
    lblCaso2A.setText(repo[0].getCriterio() + ": " + repo[0].getValor());
    lblCaso2B.setText(repo[1].getCriterio() + ": " + repo[1].getValor());
  }//GEN-LAST:event_btnLeerEstadisticaActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLeerEstadistica;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lblCaso1A;
  private javax.swing.JLabel lblCaso1B;
  private javax.swing.JLabel lblCaso2A;
  private javax.swing.JLabel lblCaso2B;
  // End of variables declaration//GEN-END:variables
}
